language: rust
rust:
- 1.39.0
- stable
- beta
- nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
- rustup component add clippy
- rustup component add rustfmt

script:
- 'if [[ "$TRAVIS_RUST_VERSION" != "1.39.0" ]]; then cargo clippy --all -- -D warnings; fi'
- cargo test --all
- cargo fmt --all -- --check
