[package]
name = "pubnub"
version = "0.1.0"
description = "PubNub Async lib based on Tokio 0.2"
repository = "https://github.com/stephenlb/pubnub-rust"
keywords = ["pubnub", "publish-subscribe", "subscribe"]
authors = ["Stephen Blum <stephen@pubnub.com>"]
readme = "readme.md"
edition = "2018"

[dependencies]
futures-executor-preview = "=0.3.0-alpha.19"
futures-util-preview = { version = "=0.3.0-alpha.19", features = ["async-await", "select-macro"] }
hyper = "=0.13.0-alpha.4"
hyper-tls = "=0.4.0-alpha.4"
json = "=0.12.0"
log = "=0.4.8"
percent-encoding = "=2.1.0"
thiserror = "=1.0.4"
tokio = "=0.2.0-alpha.6"

[dev-dependencies]
env_logger = "=0.7.1"
