[package]
name = "pubnub-rust"
version = "0.1.0"
description = "PubNub Async lib based on Tokio 0.2"
repository = "https://github.com/stephenlb/pubnub-rust"
keywords = ["pubnub", "publish-subscribe", "subscribe"]
authors = ["Stephen Blum <stephen@pubnub.com>"]
readme = "readme.md"
edition = "2018"

[dependencies]
hyper = "=0.12"
tokio-io = "=0.2.0-alpha.6"
tokio-sync = "=0.2.0-alpha.6"
