[package]
name = "pubnub"
version = "0.1.0"
description = "PubNub Async lib based on Tokio 0.2"
repository = "https://github.com/stephenlb/pubnub-rust"
keywords = ["pubnub", "publish-subscribe", "subscribe"]
authors = ["Stephen Blum <stephen@pubnub.com>"]
readme = "readme.md"
edition = "2018"

[dependencies]
thiserror = "=1.0"
hyper = "0.13.0-alpha.4"
hyper-tls = "0.4.0-alpha.4"
json = "=0.12.0"
percent-encoding = "=2.1.0"
tokio = "=0.2.0-alpha.6"

[dev-dependencies]
tokio-executor = "=0.2.0-alpha.6"
