[package]
name = "pubnub"
version = "0.1.0"
description = "PubNub Async lib based on Tokio 0.2"
repository = "https://github.com/stephenlb/pubnub-rust"
keywords = ["pubnub", "publish-subscribe", "subscribe"]
authors = ["Stephen Blum <stephen@pubnub.com>"]
readme = "readme.md"
edition = "2018"

[dependencies]
thiserror = "=1.0"
log = "=0.4"
json = "=0.12.0"
uuid = "=0.8.1"
#hyper = "=0.12"
#surf = "=1.0.2"
tokio = "=0.2.0-alpha.6"
